apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-yaml
  labels:
    app: nginx
    env: dev
spec:
  containers:
  - name: nginx-pod-yaml
    image: nginx:1.11-alpine
    ports:
    - containerPort: 80
