Vagrant.configure(2) do |config|
	config.vm.define "docker" do |devbox|
		devbox.vm.box = "ubuntu/xenial64"
    		devbox.vm.network "private_network", type: "dhcp"
#            for i in 32768..32798
#                config.vm.network :forwarded_port, guest: i, host: i
#            end
    		devbox.vm.hostname = "docker"
      		devbox.vm.provision "shell", path: "scripts/install.sh"
            devbox.vm.provision "shell", path: "scripts/bootstrp-bash.sh"
    		devbox.vm.provider "virtualbox" do |v|
    		  v.memory = 4096
    		  v.cpus = 2
    		end
	end
end
