apiVersion: v1
kind: Service
metadata:
  labels:
    name: node
    role: service
  name: grafana
spec:
  type: "LoadBalancer"
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    grafana: "true"
