= ConfigMap

== Lab Objectives

In this section, we'll configure a basic webserver that will pull it's configuration from a Kubernetes object called a *ConfigMap*.

=== Lab Structure Overview


---
---

== Lab Overview

In this lab, we'll create a reverseproxy.conf configuration file, load the configuration file into Kubernetes as a configmap object, create an nginx-service to route traffic to an nginx-configdemo deployment using the reverseproxy.conf file we created.

=== Step 1. Create a reverseproxy.conf configuration file.

In your working directory, create a file called `reverseproxy.conf` with the following content:

....
server {
    listen       80;
    server_name  localhost;

    location / {
        proxy_bind 127.0.0.1;
        proxy_pass http://127.0.0.1:3000;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
....

=== Step 2. Create the configmap object.

Run the following command to create the Kubernetes configmap object referencing the file made in the previous step.

$ `kubectl create configmap nginx-config --from-file=reverseproxy.conf`

Validate that the configmap is created and configured.

$ `kubectl describe configmap nginx-config`

=== Step 3. Create the nginx-configdemo-service service manifest

Now that the `configmap object` is created; let's create the nginx service that'll bring traffic to the nginx-configdemo deployment. Create a file named `nginx-configdemo-service.yaml` with the following content:

....
apiVersion: v1
kind: Service
metadata:
  name: configmap-nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: configdemo-nginx
  type: LoadBalancer
....

=== Step 4. Create the nginx-configdemo pod manifest

Create a pod manifest called `nginx-configdemo.yaml` with the following content:

....
apiVersion: v1
kind: Pod
metadata:
  name: configdemo-nginx
  labels:
    app: configdemo-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  - name: k8s-demo
    image: wardviaene/k8s-demo
    ports:
    - containerPort: 3000
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
        - key: reverseproxy.conf
          path: reverseproxy.conf
....

=== Step 5. Deploy the service and pod manifest.

$ `kubectl create -f nginx-configdemo-service.yaml`
service "configmap-nginx-service" created

$ `kubectl describe svc/configmap-nginx-service`
Take note of the LoadBalancer Ingress.

$ `kubectl create -f nginx-configdemo.yaml`
pod "configmap-nginx" created

$ `kubectl describe po/configmap-nginx`
Take note od the Volume section.


=== Step 6. Validate the configmap was loaded

Open a browser to the LoadBalancer Ingress:



If the configmap was properly loaded, this will open a generic hello-world application.


=== Step 7.


=== Step 8.


=== Step 9.


=== Step 10.


=== Step 11.

== Conclusion
