# Define the Vagrant environment for Ansible 101
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #Bypass issue with certs in 1.8.5
#  config.ssh.username = 'vagrant'
#  config.ssh.password = 'vagrant'
#  config.ssh.insert_key = 'false'

  (1..4).each do |i|
    config.vm.define "dev0#{i}" do |dev|
        dev.vm.box = "ubuntu/xenial64"
        dev.vm.hostname = "dev0#{i}"
        dev.vm.network "private_network", ip: "192.168.13.11#{i}"
        dev.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
        end
        dev.vm.provision :shell, path: "scripts/docker_install.sh"

#        dev.vm.provision :shell, path: "scripts/dev_install.sh"
#        dev.vm.provision :shell, path: "scripts/dns_config.sh"
#        dev.vm.provision :shell, path: "scripts/bash_config.sh"
    end
  end

end
