apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: mongo
  name: mongo
spec: 
  ports:
    - port: 27017
  selector: 
    name: mongo
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    name: mongo
spec: 
  containers: 
    - image: mongo
      name: mongo
      ports:
        - containerPort: 27017
          name: mongo
      volumeMounts:
        - name: mongo-vol
          mountPath: /data/db
  volumes:
    - name: mongo-vol
      hostPath:
        path: /data/db
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: letschat-lb
  name: letschat-lb
spec: 
  ports:
    - port: 80
      targetPort: 8080
  selector: 
    app: letschat
  type: LoadBalancer
---
apiVersion: extensions/v1beta
kind: ReplicationController
metadata:
  name: "letschat"
  labels:
    app: "letschat"
spec:
  replicas: 2
  selector:
    app: letschat
  template:
    metadata:
      labels:
        app: letschat
    spec:
      restartPolicy: Always
      containers:
      - image: "sdelements/lets-chat"
        imagePullPolicy: Always
        name: "letschat"
        env:
        - name: LCB_FILES_ENABLE
          value: "true"
        - name: LCB_FILES_PROVIDER
          value: "local"
        - name: LCB_FILES_LOCAL_DIR
          value: "uploads"
        volumeMounts:
        - mountPath: /usr/src/app/uploads
          name: uploadsvol
        ports:
        - containerPort: 8080
          name: letschat
      volumes:
      - name: uploadsvol
        ngs:
            server: us-west-2a.fs-bacb1b13.efs.us-west-2.amazonaws.com
            path: /
