apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    name: mongo
spec: 
  containers: 
    - image: mongo
      name: mongo
      ports:
        - containerPort: 27017
          name: mongo
      volumeMounts:
        - name: mongo-vol
          mountPath: /data/db
  volumes:
    - name: mongo-vol
      hostPath:
        path: /data/db
